# debug: true
image_topic: /video_publisher/frames
canny_lowThreshold: 165
canny_highThreshold: 222
canny_perBlindHorizon: 46
hough_int_rho: 1
hough_int_theta: 1
hough_threshold: 45
line_circular_buffer_size: 5
